import {
  ClipboardList,
  MapPin,
  School,
  ShieldCheck,
  Soup,
  Target,
} from "lucide-react";

export const campusServices = [
  {
    id: "campus_navigation",
    title: "校园导航",
    shortTitle: "导航",
    description: "地点查询、路线导览、地图热点联动。",
    capability: "地图导览",
    prompt: "文汇楼（图书馆）在哪？",
    emoji: "📍",
    icon: MapPin,
    accent: "from-blue-500 to-sky-400",
    tint: "bg-blue-50 text-blue-700",
  },
  {
    id: "campus_life",
    title: "校园生活",
    shortTitle: "生活",
    description: "食堂、宿舍、活动与日常问题咨询。",
    capability: "生活服务",
    prompt: "食堂怎么走？",
    emoji: "🍜",
    icon: Soup,
    accent: "from-cyan-500 to-blue-400",
    tint: "bg-cyan-50 text-cyan-700",
  },
  {
    id: "growth_plan",
    title: "学习成长",
    shortTitle: "成长",
    description: "学习规划、竞赛建议和成长路线。",
    capability: "成长规划",
    prompt: "请帮我制定一份本周学习成长计划。",
    emoji: "🎯",
    icon: Target,
    accent: "from-indigo-500 to-blue-400",
    tint: "bg-indigo-50 text-indigo-700",
  },
  {
    id: "school_culture",
    title: "校园文化",
    shortTitle: "文化",
    description: "校史文化、地标介绍与公益导览。",
    capability: "文化导览",
    prompt: "请介绍校园文化和主要地标。",
    emoji: "🏫",
    icon: School,
    accent: "from-sky-500 to-blue-500",
    tint: "bg-sky-50 text-sky-700",
  },
  {
    id: "safety_care",
    title: "安全关怀",
    shortTitle: "安全",
    description: "安全提醒、心理关怀和应急提示。",
    capability: "安全关怀",
    prompt: "校园突发情况应该怎么办？",
    emoji: "🛡",
    icon: ShieldCheck,
    accent: "from-blue-600 to-cyan-500",
    tint: "bg-blue-50 text-blue-700",
  },
  {
    id: "student_affairs",
    title: "学生事务",
    shortTitle: "事务",
    description: "流程咨询、事务办理和材料提醒。",
    capability: "事务助手",
    prompt: "学生事务办理需要准备什么材料？",
    emoji: "📋",
    icon: ClipboardList,
    accent: "from-slate-700 to-blue-500",
    tint: "bg-slate-100 text-slate-700",
  },
];

export const serviceHighlights = [
  {
    label: "Dify驱动",
    value: "统一通过服务端API代理调用Chatflow。",
    icon: ClipboardList,
  },
  {
    label: "地图联动",
    value: "解析地图ID并高亮校园地图热点。",
    icon: MapPin,
  },
  {
    label: "公益定位",
    value: "聚焦校园公共服务与学生支持。",
    icon: ShieldCheck,
  },
];
